server:
  port: 9991

spring:
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://192.168.1.12:${MYSQL-PORT:3306}/${MYSQL-DB:electricity}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://192.168.1.12:${MYSQL-PORT:3306}/${MYSQL-DB:electricity}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    lettuce:
      pool:
        max-active: 16
    host:  192.168.1.12
    password: 123456
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.12:${NACOS-PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yml
        shared-configs[0]:
          data-id: application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
          refresh: true
    sentinel:
      transport:
        port: 8716
        dashboard: localhost:8080
  profiles:
    active: dev
  klock:
    address: 192.168.1.12:6379
    password: ${spring.redis.password}
    wait-time: 20
    lease-time: 20
    database: 15

logging:
  config: classpath:logback-spring-dev.xml
  level:
    com.xiliulou.electricity.mapper: debug


iot:
  accessKey: SuoR5L5r9lJKzNiO
  accessSecret: WsCM0f7upVDgOSLWpTr0HPLgjeCEoc
  regionId: cn-shanghai
  domain: iot.cn-shanghai.aliyuncs.com
  product: iot
mns:
  access-id: SuoR5L5r9lJKzNiO
  access-key: WsCM0f7upVDgOSLWpTr0HPLgjeCEoc
  queue: aliyun-iot-a1rykKycFqu
  account-end-point: http://1640816622365812.mns.cn-shanghai.aliyuncs.com/


storage:
  ### oss:oss-cn-beijing.aliyuncs.com minio:http://172.21.0.9:9000
  ossEndpoint: oss-cn-beijing.aliyuncs.com
  minioEndpoint: http://172.21.0.9:9000
  ### oss:SuoR5L5r9lJKzNiO
  accessKeyId: SuoR5L5r9lJKzNiO
  ### oss:WsCM0f7upVDgOSLWpTr0HPLgjeCEoc
  accessKeySecret: WsCM0f7upVDgOSLWpTr0HPLgjeCEoc
  ### minio:minioadmin
  accessKey: minioadmin
  ### minio:minioadmin
  secretKey: minioadmin
  ### oss:wm-xiliulou-test minio:xll
  bucketName: wm-xiliulou-test
  minioBucketName: device
  ### oss:img.wm.xiliulou.com
  urlPrefix: img.wm.xiliulou.com
  dir: qiji/
  ### oss:0 minio:1
  isUseOSS: 0
